### PR TITLE
upgrading the package version so that it reflects the breaking change…

### LINKED ISSUE #59: Breaking change on 2.7.0
### Problem
Changes to the way the module exports its functions seem to cause breaking changes due to #56.
Instead of exporting the `sendemail` function like this:
```javascript
module.exports = sendemail;
```
It is now being exported like this: 
```javascript
module.exports.email = sendemail;
```
This causes the error `TypeError: email is not a function` if your code is still expecting the old version.

### How to fix
The issue can be fixed by changing how you import `sendemail` to reflect the above:
Replace
```javascript
const email = require('sendemail')
email.set_template_directory('./path/to/templates')
```
with
```javascript
const { email, set_template_directory } = require('sendemail')
set_template_directory('./lib/emails/templates')
```
Or if you're on an older version of node:
```javascript
const sendemail = require('sendemail')
const email = sendemail.email
const set_template_directory = sendemail.set_template_directory
set_template_directory('./lib/emails/templates')
```

Alternatively, change your package.json to specify a version older than 2.7.0 - maybe a better fix if you're using this in lots of different files.

### PR DESCRIPTION
**Pull request by shouston3**
Fixes #59 

So that it reflects the breaking changes that were implemented

### CODE REVIEW

**Comment by nelsonic** [comment]
thanks @shouston3 👍

**Comment by nelsonic** [comment]
@otajor `sendemail@3.0.0` on NPM. thanks again for your _eagle_ eye on this! ❤️  ✅  🚀
