### ISSUE TITLE
Breaking change on 2.7.0

### ISSUE THREAD

**Issue by otajor** [dwyl/sendemail#59]
### Problem
Changes to the way the module exports its functions seem to cause breaking changes due to #56.
Instead of exporting the `sendemail` function like this:
```javascript
module.exports = sendemail;
```
It is now being exported like this: 
```javascript
module.exports.email = sendemail;
```
This causes the error `TypeError: email is not a function` if your code is still expecting the old version.

### How to fix
The issue can be fixed by changing how you import `sendemail` to reflect the above:
Replace
```javascript
const email = require('sendemail')
email.set_template_directory('./path/to/templates')
```
with
```javascript
const { email, set_template_directory } = require('sendemail')
set_template_directory('./lib/emails/templates')
```
Or if you're on an older version of node:
```javascript
const sendemail = require('sendemail')
const email = sendemail.email
const set_template_directory = sendemail.set_template_directory
set_template_directory('./lib/emails/templates')
```

Alternatively, change your package.json to specify a version older than 2.7.0 - maybe a better fix if you're using this in lots of different files.

**Comment by nelsonic** [comment]
@shouston3 can you _help_ with this? (_I think @otajor is **right**_!) 🤔

**Comment by otajor** [comment]
I think this is the desired/expected behaviour in order to be able to stub easily with `sinon.stub(sendemail, 'email')` - I don't think it's an unintentional bug.

But should probably have been pushed as v3.0.0 rather than v2.7.0. Maybe @shouston3 should have been clearer that this was a breaking change?

**Comment by nelsonic** [comment]
@otajor agreed. let's do that.

**Comment by shouston3** [comment]
Sorry, I upgraded the readme, but forgot to upgrade the package version

**Comment by nelsonic** [comment]
@shouston3 _definitely_ not _your_ fault. all you did was make this package _bettererererer_!! 😍 
It's **100% my bad** for not paying closer attention when reviewing the PR. 😖 
We're just lucky @otajor is "_on the ball_"... ☔️  🥇

**Comment by Danwhy** [comment]
Is it possible to unpublish versions on npm? Because 2.7.0 still exists with the breaking change, it's still automatically upgrading versions 2.6.0 and below and breaking them

**Comment by nelsonic** [comment]
@Danwhy oh... dang! I don't think there is a way to _unpublish_ anymore since the LeftPad Fiasco... 
What _would_ be a good course of action here...? 🤔

**Comment by Danwhy** [comment]
@nelsonic It seems if the release is more than 24 hours old, you have to [contact npm support](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy)

**Comment by nelsonic** [comment]
@Danwhy I have sent them an email:
![image](https://cloud.githubusercontent.com/assets/194400/22464587/8020648a-e7af-11e6-81de-227f1bf7df73.png)
This should be done shortly.
Thanks again for letting us know this was hurting you. 👍  😞

**Comment by roryc89** [comment]
I don't know if this is now possible but it may be best to release another minor change that reverts the API back to before the major change was made. That way any users of the module with a `^` that automatically upgrades to the most recent minor change will not upgrade to the breaking change.

**Comment by nelsonic** [comment]
@roryc89 what is your NPM username? (_happy for someone `else` to resolve this..._)

**Comment by roryc89** [comment]
Hi @nelsonic it's `roryc89`

**Comment by nelsonic** [comment]
@roryc89 you can publish a new version on the 2.x.x stream
https://www.npmjs.com/package/sendemail
please let me know if you need help with this... 👍
